vich_uploader:
    db_driver: orm

    mappings:
       avatars:
           uri_prefix: /images/uploads
           upload_destination: '%kernel.project_dir%/public/images/uploads'
        #    namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        #    delete_on_update: true
        #    delete_on_remove: true
